config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get "/about" => "pages#about"

  resources :posts, except: [:show]

  resources :posts, only: [:show] do
    resources :comments, only: [:create, :destroy], shallow: true
  end

  resources :users, only: [:new, :create, :index]

  resources :sessions, only: [:new, :create, :destroy]
  get "/login" => "sessions#new"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" },
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_attachment :photo,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  def youtube_link
    "https://youtu.be/#{self.embed_url}"
  end

  def embed_link
    "https://www.youtube.com/embed/#{self.embed_url}"
  end

  def self.videos
    self.where "embed_url <> ''"
  end

  def self.photos
    self.where "photo_file_name IS NOT NULL"
  end

  def self.text_posts
    self.where "text_post <> ''"
  end

  def has_image?
    self.photo.present?
  end

  def has_text?
    self.text_post.present?
  end

  def has_video?
    self.embed_url.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts
  has_many :comments

  validates :email, presence: true, uniqueness: true

  def full_name
    f_name + ' ' + l_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    redirect_to login_path, alert: "Not authorized - you must be logged in!" if current_user.nil?
  end

 def is_admin(user)
    user.is_admin
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    if @comment.save
      redirect_to posts_path(params[:post_id])
    else
      render posts_path(params[:post_id])
    end
  end

  def destroy
    comment = Comment.find params[:id]
    if comment.user == current_user
      comment.destroy
    end
    redirect_to post_path(comment.post)
  end

private

  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  def index
    if params[:video]
      @posts = Post.videos
    elsif params[:photo]
      @posts = Post.photos
    elsif params[:text_posts]
      @posts = Post.text_posts
    else
      @posts = Post.all
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
    @comment = Comment.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
        redirect_to posts_path
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = @post.destroy

    flash[:post] = "'#{@post.title}' removed!"
    redirect_to posts_path
  end

private

  def clean_youtube_url(url)
    url = url.gsub /https:\/\//, ""
    url = url.gsub /http:\/\//, ""
    url = url.gsub /(youtu.be\/|www.youtube.com\/watch\?v=|youtube.com\/watch\?v=)/, ""
    url = url.gsub /&.*$/, ""
  end

  def post_params
    params[:post][:embed_url] = clean_youtube_url(params[:post][:embed_url])
    params.require(:post).permit(
      :title,
      :text_post,
      :photo,
      :embed_url
    )
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def authorize
    if current_user != @post.user
      redirect_to post_path(@post), alert: "Not authorized - not your post buddy!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You are logged in and in formation!"
    else
      flash.now.alert = "Invalid login!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out, see you next time!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up to get in formation!"
      redirect_to root_path
    else
      render :new
  end
end

private

  def user_params
    params.require(:user).permit(:f_name, :l_name, :email, :password, :password_confirmation)
  end

  def authorize_modify_content
    if (current_user != User.find(params[:id])) && !current_user.is_admin
      redirect_to root_path
    end
  end

  def authorize_users_view
    if !current_user.is_admin
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Beyhive</title>
  <link rel="icon" type="jpg/png" href="http://www.clker.com/cliparts/P/q/6/5/Z/S/small-bee-th.png">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body class="container">
  <nav class="navbar navbar-inverse">
    <ul class="nav nav-pills">
        <% if current_user %>
          <li class="welcome">Welcome, <%= current_user.f_name %></li>
          <li><%= link_to 'Logout', session_path('dummy'), method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li id="signup_link"><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
          <li><%= link_to "Home", root_path %></li>
          <li><%=link_to "About", about_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" target="_blank">More Beyonce <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown"><a href="http://www.beyonce.com/" target="_blank">Official Beyonce</a></li>
              <li class="dropdown"><a href="http://www.beyonce.com/tour/" target="_blank">Beyonce Tour</a></li>
              <li class="dropdown"><a href="http://shop.beyonce.com/" target="_blank">Shop Beyonce</a></li>
              <li class="dropdown"><a href="http://thisistheread.com/" target="_blank">The Read</a></li>
            </ul>
          </li>
      </ul>
  </nav>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">About The BeyHive<small>
  <br>
  The Beyhive is the only place for users to post all things related
  <strong>exclusively</strong> to Beyonce. You can post your favorite videos,
  images, and text posts for the world to see. It's time to get in
  formation and share your love for Beyonce!
</small></h1>
<img class="col-xs-12 img-responsive center-block" src="https://i.imgur.com/2ehjwVM.jpg">

app/views/pages/home.html.erb
<div class="container-fluid">
  <h1 class="text-center home_header">The BeyHive</h1>
  <div class="row">
    <div class="col-xs-12 center-block">
      <div class="hovereffect">
        <img id="home_page_imgs" class="img-responsive" src="https://i.imgur.com/sDqVq8B.jpg" alt="">
        <div class="overlay">
           <h2>Videos</h2>
           <a class="info" <%= link_to "Videos", posts_path(video: true)%><% link_to  posts_path(video: true) %></a>
        </div>
      </div>
    </div>
    <div class="col-xs-12 center-block">
      <div class="hovereffect">
        <img class="img-responsive" src="https://i.imgur.com/nA9Hx5a.jpg" alt="">
        <div class="overlay">
           <h2>Photos</h2>
           <a class="info" <%= link_to "Photos", posts_path(photo: true)%><% link_to  posts_path(photo: true)%></a>
        </div>
      </div>
    </div>
    <div class="col-xs-12 center-block">
      <div class="hovereffect">
        <img class="img-responsive" src="https://i.imgur.com/fkbfcX4.jpg" alt="">
        <div class="overlay">
           <h2>Text</h2>
           <a class="info" <% link_to posts_path(text_posts: true)%><%= link_to "Text", posts_path(text_posts: true)%></a>
        </div>
      </div>
    </div>
    <div class="col-xs-12 center-block">
      <div class="hovereffect">
        <img class="img-responsive" src="https://i.imgur.com/F9rTKEA.jpg" alt="">
        <div class="overlay">
           <h2>All</h2>
           <a class="info" <% link_to "All", posts_path%><%= link_to "All", posts_path %></a>
        </div>
      </div>
    </div>
     <div class="col-xs-12 center-block">
      <div class="hovereffect">
        <img class="img-responsive" src="https://i.imgur.com/DDIQTVR.jpg" alt="">
        <div class="overlay">
           <h2>About</h2>
           <a class="info" <%link_to "About", about_path %><%=link_to "About", about_path %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_comment.html.erb
<div class="add_comment" class="lead">
  <h4>Add a comment!</h4>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :text, {class: "form-control", rows: "3"} %>
    <%= f.submit "Submit Comment", {class: "btn btn-primary"} %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post container">
  <h4><%= post.title%></h4>
     <% if post.has_video? %>
      <iframe class="video-embed" src="<%= post.embed_link %>"
      width= "600" height= "450" frameborder="0"
      allowfullscreen></iframe>
      <% end %>

      <% if post.has_image? %>
        <img src="<%= post.photo %>" width="600">
      <% end %>

      <% if post.has_text? %>
        <p style= "width: 600"><%= post.text_post %></p>
      <% end %>
     <div class="comment_box">
      <h5>Comments:</h5>
      <% post.comments.each do |comment| %>
        <p><strong><%= comment.user.full_name %></strong> said:</p>
        <%= comment.text %>
        <% if current_user == comment.user %>
          <%= link_to "x", comment_path(comment),
          method: :delete, class: "btn btn-xs btn-danger",
          :data => {:confirm => "You Sure?"} %>
        <% end %>
      <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container" id="add_post_container">
  <h1 class="text-center">Edit your post!</h1>

  <div class="col-md-4 col-md-offset-4">
    <%= form_for @post, html: { multipart: true } do |f| %>
     <div class="form-group">
        <%= f.label :title, "Title" %>
        <input class="form-control" placeholder="Title" <%=f.text_field :title %>
      </div>
      <div class="form-group">
        <%= f.label :text_post, "Text Post" %>
        <input class="form-control" id="text_box" placeholder="Text Post" <%=f.text_field :text_post %>
      </div>
      <div class="form-group">
        <%= f.label :embed_url, "YouTube ID" %>
        <input class="form-control" placeholder="Youtube ID" <%=f.text_field :embed_url%>
      </div>
      <div class="form-group">
         <%= f.label :photo, "Photo File" %>
        <input class="form-control" placeholder="Photo URL" <%=f.file_field :photo %>
      </div>
      <div class="actions"><%= f.submit "Submit changes!" %></div>
  </div>
   <% end %>
   <%= link_to "Back to all posts!", posts_path %>
   <%= link_to "Back to post", post_path(@post), :class => "Show" %>
</div>

app/views/posts/index.html.erb
<div class="row text-center" class="container">
  <div class="post_container" class="container">
    <h1 class="text-center">Posts</h1>
      <div class="new_post">
        <% if current_user %>
          <%= link_to "Create a new post!", new_post_path, {class: "btn btn-primary"}%>
        <% end %>
      </div>
      <% @posts.order("created_at desc").each do |post| %>
        <%= render "post", post: post %>
        <div class="post_links">
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "Show post", post_path(post), :class => "Show" %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <% if current_user == post.user %>
            <%= link_to "Edit post", edit_post_path(post), :class => "Edit" %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center">Add a new post!</h1>

  <div class="col-md-4 col-md-offset-4">
    <%= form_for @post, html: { multipart: true } do |f| %>
     <div class="form-group">
        <%= f.label :title, "Title" %>
        <input class="form-control" placeholder="Title" <%=f.text_field :title %>
      </div>
      <div class="form-group">
        <%= f.label :text_post, "Text Post" %>
        <input class="form-control" id="text_box" placeholder="Text Post" <%=f.text_field :text_post %>
      </div>
      <div class="form-group">
        <%= f.label :embed_url, "YouTube Link" %>
        <input class="form-control" placeholder="Youtube Link" <%=f.text_field :embed_url%>
      </div>
      <div class="form-group">
         <%= f.label :photo, "Photo File" %>
        <input class="form-control" placeholder="Photo URL" <%=f.file_field :photo %>
      </div>
      <div class="actions"><%= f.submit "Submit!" %></div>
  </div>
   <% end %>
</div>


<% if @post.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
        <ul class="list-unstyled">
          <% for message in @post.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
<% end %>

app/views/posts/show.html.erb
<%= render "post", post: @post %>
<%= render "comment" %>

<% if @post.user == current_user %>
&nbsp;&nbsp;|&nbsp;&nbsp;
<%= link_to "Back to all posts!", posts_path %>
&nbsp;&nbsp;|&nbsp;&nbsp;
<%= link_to "Delete Post!", post_path, data:
{confirm: "Are you sure you want to delete this post?"}, :method => "Delete" %>
&nbsp;&nbsp;|&nbsp;&nbsp;
<%= link_to "Edit post!", edit_post_path(@post), :class => "Edit" %>
&nbsp;&nbsp;|&nbsp;&nbsp;
<% end %>

app/views/users/new.html.erb
<div class="container-fluid" id="sign_up_container">
  <div class="sign_up">
    <h1 class="text-center">Sign Up!</h1>
      <div class="col-md-4 col-md-offset-4">
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :f_name, "First Name" %>
            <input class="form-control" placeholder="First Name" <%=f.text_field :f_name %>
          </div>
          <div class="form-group">
            <%= f.label :l_name, "Last Name" %>
            <input class="form-control" placeholder="Last Name" <%=f.text_field :l_name %>
          </div>
          <div class="form-group">
            <%= f.label :email, "email" %>
            <input class="form-control" placeholder="email" <%=f.text_field :email %>
          </div>
          <div class="form-group">
            <%= f.label :password, "Password" %>
            <input class="form-control" placeholder="Password" <%=f.password_field :password %>
          </div>
            <div class="form-group">
            <%= f.label :password_confirmation, "Password Confirmation" %>
            <input class="form-control" placeholder="Please enter your password again!"
            <%=f.password_field :password_confirmation %>
          </div>
      <div class="actions"><%= f.submit "Submit!", {class: "btn btn-info"} %></div>
    </div>
  </div>
</div>
      <% end %>

<% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul class="list-unstyled">
        <% for message in @user.errors.full_messages %>
          <%= message %>
        <% end %>
      </ul>
<% end %>
</div>